import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Lexend,
  Akshar,
  Roboto,
  Inter,
  IBM_Plex_Mono,
  Chakra_Petch,
  Alata,
  Righteous,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SessionWrapper from "@/components/SessionWrapper";
import AppWalletProvider from "@/components/WalletProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

const akshar = Akshar({
  subsets: ["latin"],
  variable: "--font-akshar",
  weight: ["400", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"],
});

const chakra = Chakra_Petch({
  subsets: ["latin"],
  variable: "--font-chakra",
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const ibm = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-ibm-mono",
  weight: ["400", "600", "700"],
});

const alata = Alata({
  subsets: ["latin"],
  variable: "--font-alata",
  weight: ["400"],
});
const righteous = Righteous({
  subsets: ["latin"],
  variable: "--font-righteous",
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${akshar.variable} ${righteous.variable} ${roboto.variable} ${inter.variable} ${ibm.variable} ${chakra.variable} ${alata.variable}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWalletProvider>
          <SessionWrapper>
            <Toaster position="bottom-right" reverseOrder={false} />
            {children}
          </SessionWrapper>
        </AppWalletProvider>
      </body>
    </html>
  );
}
